default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password:

development:
  <<: *default
  database: goku_ecommerce_development

test:
  <<: *default
  database: goku_ecommerce_test